- hosts: webserver
  tasks:
          - name: "Deleting Webserver"
            package:
                    name:
                            - "httpd"
                            - "php"
                    state: absent

          - name: "Deleting Website Volume"
            file:
                    state: "absent"
                    path: "/website"

          - name: "Deleting Website Directory"
            file:
                    state: "absent"
                    path: "/var/www/html/index.php"

- hosts: Loadbalancer
  tasks:
         - name: "Deleting LB"
           package:
                   name: "haproxy"
                   state: absent

         - name: "Configure LB"
           file:
                   state: "absent"
                   path: "/etc/haproxy"
